name: build-pkgs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    strategy:
      matrix:
        repos:
          - neovim-git
          - vim-git
          - vim-git-runtime
          - tmux-git
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: weiliang1503/build-aur-action@master
        with:
          repo-name: ${{ matrix.repos }}
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./**/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
