name: build-pkgs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    strategy:
      matrix:
        repos:
          - neovim-git
          - tmux-git
          - flat-remix
          - github.com/gamoutatsumi/alacritty-mold-git
          - github.com/gamoutatsumi/xremap-x11-bin
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: gamoutatsumi/build-aur-action@master
        with:
          repo-name: ${{ matrix.repos }}
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./**/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
